import React, { useState } from 'react';
import './App.css';

const words = [
  {"japanese": "憧れる あこがれる", "korean": "동경하다"},
  {"japanese": "味わう あじわう", "korean": "맛보다"},
  {"japanese": "預かる あずかる", "korean": "맡다"},
  {"japanese": "焦る あせる", "korean": "초조해하다"},
  {"japanese": "与える あたえる", "korean": "주다, 수여하다"},
  {"japanese": "温める あたためる", "korean": "데우다"},
  {"japanese": "当たる あたる", "korean": "맞다, 해당하다"},
  {"japanese": "扱う あつかう", "korean": "취급하다"},
  {"japanese": "暴れる あばれる", "korean": "난폭하게 굴다, 날뛰다"},
  {"japanese": "溢れる あふれる", "korean": "넘쳐나다, 흔하다"},
  {"japanese": "甘やかす あまやかす", "korean": "응석 부리게 하다"},
  {"japanese": "編む あむ", "korean": "짜다, 뜨게질하다"},
  {"japanese": "謝る あやまる", "korean": "사과하다, 사죄하다"},
  {"japanese": "荒れる あれる", "korean": "거칠어지다"},
  {"japanese": "慌てる あわてる", "korean": "당황하다, 허둥거리다"},
  {"japanese": "生かす いかす", "korean": "살리다, 발휘하다, 활용하다"},
  {"japanese": "維持する いじする", "korean": "유지하다"},
  {"japanese": "至る いたる", "korean": "이르다"},
  {"japanese": "一致する いっちする", "korean": "일치하다"},
  {"japanese": "祈る いのる", "korean": "빌다, 기원하다"},
  {"japanese": "祝う いわう", "korean": "축하하다"},
  {"japanese": "植える うえる", "korean": "심다"},
  {"japanese": "承る うけたまわる", "korean": "삼가 듣다, 받잡다"},
  {"japanese": "失う うしなう", "korean": "잃어버리다, 놓치다"},
  {"japanese": "薄れる うすれる", "korean": "엷어지다, 약해지다"},
  {"japanese": "疑う うたがう", "korean": "의심하다"},
  {"japanese": "打ち明ける うちあける", "korean": "고백하다"},
  {"japanese": "映す うつす", "korean": "비추다"},
  {"japanese": "訴える うったえる", "korean": "고소하다, 호고하다"},
  {"japanese": "奪う うばう", "korean": "뺏다"},
  {"japanese": "埋める うめる", "korean": "묻다, 메우다"},
  {"japanese": "裏切る うらぎる", "korean": "배반하다"},
  {"japanese": "占う うらなう", "korean": "점치다"},
  {"japanese": "売り切れる うりきれる", "korean": "품절되다"},
  {"japanese": "追い込む おいこむ", "korean": "몰아넣다"},
  {"japanese": "追いつく おいつく", "korean": "따라붙다, 따라잡다"},
  {"japanese": "追う おう", "korean": "좇다"},
  {"japanese": "覆う おおう", "korean": "덮다, 씌우다, 가리다"},
  {"japanese": "犯す おかす", "korean": "(죄를) 범하다, (법을) 어기다"},
  {"japanese": "補う おぎなう", "korean": "보충하다, 메우다"},
  {"japanese": "贈る おくる", "korean": "선물하다"},
  {"japanese": "抑える おさえる", "korean": "억누르다"},
  {"japanese": "収める おさめる", "korean": "거두다, 넣다, 담다"},
  {"japanese": "納める おさめる", "korean": "납입하다"},
  {"japanese": "恐れる おそれる", "korean": "무서워하다, 두려워하다"},
  {"japanese": "落ち着く おちつく", "korean": "침착하다, 안정되다"},
  {"japanese": "訪れる おとずれる", "korean": "방문하다"},
  {"japanese": "劣る おとる", "korean": "열등하다, 뒤떨어지다"},
  {"japanese": "驚く おどろく", "korean": "놀라다"},
  {"japanese": "抱える かかえる", "korean": "안다, 떠맡다"},
  {"japanese": "輝く かがやく", "korean": "빛나다"},
  {"japanese": "係る かかわる", "korean": "관련되다, 관여하다"},
  {"japanese": "限る かぎる", "korean": "한정하다"},
  {"japanese": "欠く かく", "korean": "부족하다, 없다"},
  {"japanese": "隠す かくす", "korean": "숨기다"},
  {"japanese": "重ねる かさねる", "korean": "겹치다, 중복되다"},
  {"japanese": "貸し出す かしだす", "korean": "대출하다"},
  {"japanese": "稼ぐ かせぐ", "korean": "(돈, 시간, 점수를) 벌다"},
  {"japanese": "傾く かたむく", "korean": "(위치, 마음, 사상이) 기울다"},
  {"japanese": "偏る かたよる", "korean": "기울다, 치우치다(편중)"},
  {"japanese": "語る かたる", "korean": "말하다"},
  {"japanese": "叶う かなう", "korean": "이루어지다"},
  {"japanese": "庇う かばう", "korean": "감싸다, 비호하다"},
  {"japanese": "我慢する がまんする", "korean": "참다"},
  {"japanese": "乾く かわく", "korean": "마르다(건조)"},
  {"japanese": "観察する かんさつする", "korean": "관찰하다"},
  {"japanese": "乾燥する かんそうする", "korean": "건조하다"},
  {"japanese": "刻む きざむ", "korean": "새기다, 조각하다"},
  {"japanese": "競う きそう", "korean": "경쟁하다"},
  {"japanese": "鍛える きたえる", "korean": "단련하다"},
  {"japanese": "急増する きゅうぞうする", "korean": "급증하다"},
  {"japanese": "区切る くぎる", "korean": "구분하다, 구획 짓다"},
  {"japanese": "崩れる くずれる", "korean": "무너지다, 쓰러지다"},
  {"japanese": "悔やむ くやむ", "korean": "분하게 여기다, 후회하다"},
  {"japanese": "繰り返す くりかえす", "korean": "반복하다"},
  {"japanese": "削る けずる", "korean": "깎다, 줄이다, 삭감하다"},
  {"japanese": "貢献する こうけんする", "korean": "공헌하다"},
  {"japanese": "超える こえる", "korean": "넘다"},
  {"japanese": "凍る こおる", "korean": "얼다"},
  {"japanese": "克服する こくふくする", "korean": "극복하다"},
  {"japanese": "焦げる こげる", "korean": "타다"},
  {"japanese": "試みる こころみる", "korean": "시도해 보다"},
  {"japanese": "異なる ことなる", "korean": "상이하다, 다르다"},
  {"japanese": "断る ことわる", "korean": "거절하다"},
  {"japanese": "転ぶ ころぶ", "korean": "구르다, 넘어지다"},
  {"japanese": "探す さがす", "korean": "찾다"},
  {"japanese": "逆らう さからう", "korean": "거스르다"},
  {"japanese": "叫ぶ さけぶ", "korean": "외치다"},
  {"japanese": "避ける さける", "korean": "피하다, 꺼리다"},
  {"japanese": "下げる さげる", "korean": "(위치, 값 등을) 내리다"},
  {"japanese": "支える ささえる", "korean": "지탱하다, 떠받치다"},
  {"japanese": "差し上げる さしあげる", "korean": "드리다, 바치다"},
  {"japanese": "指す さす", "korean": "가리키다"},
  {"japanese": "誘う さそう", "korean": "권유하다"},
  {"japanese": "妨げる さまたげる", "korean": "방해하다"},
  {"japanese": "騒ぐ さわぐ", "korean": "떠들다"},
  {"japanese": "仕上げる しあげる", "korean": "일을 끝내다"},
  {"japanese": "持参する じさんする", "korean": "지참하다"},
  {"japanese": "沈む しずむ", "korean": "가라앉다"},
  {"japanese": "湿る しめる", "korean": "축축해지다, 습기차다"},
  {"japanese": "招待する しょうたいする", "korean": "초대하다"},
  {"japanese": "救う すくう", "korean": "구하다, 구조하다"},
  {"japanese": "優れる すぐれる", "korean": "우수하다"},
  {"japanese": "勧める すすめる", "korean": "권하다, 추천하다"},
  {"japanese": "捨てる すてる", "korean": "버리다"},
  {"japanese": "済む すむ", "korean": "끝나다(해결)"},
  {"japanese": "狭める せばめる", "korean": "좁히다"},
  {"japanese": "迫る せまる", "korean": "육박하다, 다가오다"},
  {"japanese": "遭遇する そうぐうする", "korean": "조우하다, 우연히 만나다"},
  {"japanese": "添える そえる", "korean": "첨부하다, 덧붙이다"},
  {"japanese": "属する ぞくする", "korean": "속하다"},
  {"japanese": "注ぐ そそぐ", "korean": "붓다, 따르다"},
  {"japanese": "備える そなえる", "korean": "준비하다, 구비하다"},
  {"japanese": "染める そめる", "korean": "물들이다"},
  {"japanese": "揃う そろう", "korean": "갖추어지다"},
  {"japanese": "耐える たえる", "korean": "참다, 인내하다"},
  {"japanese": "倒す たおす", "korean": "쓰러뜨리다"},
  {"japanese": "倒れる たおれる", "korean": "쓰러지다"},
  {"japanese": "確かめる たしかめる", "korean": "확인하다"},
  {"japanese": "経つ たつ", "korean": "경과하다, 지나다"},
  {"japanese": "達する たっする", "korean": "달하다"},
  {"japanese": "頼む たのむ", "korean": "부탁하다"},
  {"japanese": "黙る だまる", "korean": "잠자코 있다, 침묵하다"},
  {"japanese": "保つ たもつ", "korean": "유지하다, 보존하다"},
  {"japanese": "近づく ちかづく", "korean": "다가가다"},
  {"japanese": "縮む ちぢむ", "korean": "줄어들다, 쪼글쪼글해지다"},
  {"japanese": "散らす ちらす", "korean": "어지르다, 흩뜨리다"},
  {"japanese": "費やす ついやす", "korean": "다 소비하다"},
  {"japanese": "通じる つうじる", "korean": "(언어, 마음 등이) 통하다"},
  {"japanese": "捕まる つかまる", "korean": "붙잡히다"},
  {"japanese": "就く つく", "korean": "(지위에) 오르다, 취임하다"},
  {"japanese": "続く つづく", "korean": "계속되다"},
  {"japanese": "務める つとめる", "korean": "(임무를) 맡다, 역할을 다하다"},
  {"japanese": "繋がる つながる", "korean": "연결되다, 이어지다"},
  {"japanese": "潰れる つぶれる", "korean": "찌부러지다, 망하다"},
  {"japanese": "詰まる つまる", "korean": "막히다, 꽉 차다"},
  {"japanese": "積み重ねる つみかさねる", "korean": "겹겹이 쌓다, 쌓아 올리다"},
  {"japanese": "積む つむ", "korean": "쌓다"},
  {"japanese": "詰め込む つめこむ", "korean": "채워 넣다"},
  {"japanese": "連れる つれる", "korean": "동반하다"},
  {"japanese": "出来上がる できあがる", "korean": "완성되다"},
  {"japanese": "適応する てきおうする", "korean": "적응하다"},
  {"japanese": "徹底する てっていする", "korean": "철저하다"},
  {"japanese": "転じる てんじる", "korean": "<자동사> 바뀌다 <타동사> 바꾸다"},
  {"japanese": "伝染する でんせんする", "korean": "전염되다"},
  {"japanese": "問い合わせる といあわせる", "korean": "문의하다"},
  {"japanese": "溶かす とかす", "korean": "녹이다"},
  {"japanese": "届ける とどける", "korean": "보내다, 배달하다, (관청 등에) 신고하다"},
  {"japanese": "整える ととのえる", "korean": "정돈하다"},
  {"japanese": "伴う ともなう", "korean": "동반하다"},
  {"japanese": "取り上げる とりあげる", "korean": "집어 들다, 채택하다"},
  {"japanese": "取り扱う とりあつかう", "korean": "취급하다"},
  {"japanese": "取り入れる とりいれる", "korean": "받아들이다"},
  {"japanese": "取り組む とりくむ", "korean": "맞붙다, 몰두하다"},
  {"japanese": "取り除く とりのぞく", "korean": "제거하다, 없애다"},
  {"japanese": "眺める ながめる", "korean": "바라보다, 조망하다"},
  {"japanese": "嘆く なげく", "korean": "한탄하다"},
  {"japanese": "納得する なっとくする", "korean": "납득하다"},
  {"japanese": "悩む なやむ", "korean": "고민하다"},
  {"japanese": "鳴る なる", "korean": "울리다"},
  {"japanese": "慣れる なれる", "korean": "적응되다, 익숙하다"},
  {"japanese": "担う になう", "korean": "짊어지다, 메다"},
  {"japanese": "抜く ぬく", "korean": "뽑다, 빼다"},
  {"japanese": "願う ねがう", "korean": "원하다, 바라다"},
  {"japanese": "逃す のがす", "korean": "놓치다"},
  {"japanese": "伸ばす のばす", "korean": "늘리다, 신장시키다"},
  {"japanese": "伸びる のびる", "korean": "늘다, 신장하다"},
  {"japanese": "述べる のべる", "korean": "진술하다"},
  {"japanese": "拝見する はいけんする", "korean": "보다, 읽다의 겸양"},
  {"japanese": "測る はかる", "korean": "측량하다, 재다"},
  {"japanese": "吐き出す はきだす", "korean": "토해내다, 내뱉다"},
  {"japanese": "励む はげむ", "korean": "힘쓰다"},
  {"japanese": "外す はずす", "korean": "떼다, 풀다"},
  {"japanese": "外れる はずれる", "korean": "벗겨지다, 제외되다"},
  {"japanese": "果たす はたす", "korean": "완수하다, 다하다"},
  {"japanese": "離れる はなれる", "korean": "멀어지다, 떨어지다"},
  {"japanese": "省く はぶく", "korean": "생략하다"},
  {"japanese": "冷える ひえる", "korean": "차가워지다, 추워지다"},
  {"japanese": "引き受ける ひきうける", "korean": "떠맡다"},
  {"japanese": "引き渡す ひきわたす", "korean": "넘겨주다, 인도하다"},
  {"japanese": "広げる ひろげる", "korean": "넓히다"},
  {"japanese": "増える ふえる", "korean": "늘다, 증가하다"},
  {"japanese": "深める ふかめる", "korean": "깊게 하다"},
  {"japanese": "含む ふくむ", "korean": "포함하다"},
  {"japanese": "膨らむ ふくらむ", "korean": "(꿈, 계획 등이) 부풀다"},
  {"japanese": "防ぐ ふせぐ", "korean": "막다, 방지하다"},
  {"japanese": "踏み出す ふみだす", "korean": "내딛다, 착수하다"},
  {"japanese": "踏む ふむ", "korean": "밟다"},
  {"japanese": "振り返る ふりかえる", "korean": "뒤돌아보다, 돌이켜보다"},
  {"japanese": "振り込む ふりこむ", "korean": "납입하다, 불입하다"},
  {"japanese": "振り向く ふりむく", "korean": "뒤돌아보다"},
  {"japanese": "触れる ふれる", "korean": "<자동사> 닿다 <타동사> 만지다"},
  {"japanese": "隔てる へだてる", "korean": "사이를 두다, 칸을 두다"},
  {"japanese": "減る へる", "korean": "줄다, 감소하다"},
  {"japanese": "保存する ほぞんする", "korean": "보존하다"},
  {"japanese": "参る まいる", "korean": "오다, 가다의 겸양"},
  {"japanese": "任せる まかせる", "korean": "맡기다"},
  {"japanese": "負ける まける", "korean": "지다"},
  {"japanese": "混ぜる まぜる", "korean": "섞다, 혼합하다"},
  {"japanese": "纏める まとめる", "korean": "정리하다"},
  {"japanese": "惑わす まどわす", "korean": "현혹시키다, 유혹하다"},
  {"japanese": "招く まねく", "korean": "초대하다, 부르다"},
  {"japanese": "迷う まよう", "korean": "망설이다, 헤매다"},
  {"japanese": "見い出す みいだす", "korean": "찾아내다, 발견하다"},
  {"japanese": "磨く みがく", "korean": "닦다, 연마하다"},
  {"japanese": "満たす みたす", "korean": "채우다, 충족시키다"},
  {"japanese": "乱れる みだれる", "korean": "흐트러지다, 혼란해지다"},
  {"japanese": "見直す みなおす", "korean": "다시 보다, 재검토하다"},
  {"japanese": "見慣れる みなれる", "korean": "눈에 익숙하다"},
  {"japanese": "見分ける みわける", "korean": "분간하다, 분별하다"},
  {"japanese": "結ぶ むすぶ", "korean": "맺다, 묶다"},
  {"japanese": "恵まれる めぐまれる", "korean": "혜택받다, 은혜받다"},
  {"japanese": "目指す めざす", "korean": "지향하다, 목표하다"},
  {"japanese": "申し上げる もうしあげる", "korean": "말씀드리다(言う의 겸양)"},
  {"japanese": "燃える もえる", "korean": "타다"},
  {"japanese": "潜る もぐる", "korean": "잠수하다"},
  {"japanese": "用いる もちいる", "korean": "쓰다, 이용하다"},
  {"japanese": "基づく もとづく", "korean": "근거하다"},
  {"japanese": "求める もとめる", "korean": "구하다(요구)"},
  {"japanese": "催す もよおす", "korean": "개최하다"},
  {"japanese": "盛り上がる もりあがる", "korean": "(분위기가) 고조되다, 솟아오르다"},
  {"japanese": "漏れる もれる", "korean": "새다(누수)"},
  {"japanese": "養う やしなう", "korean": "기르다, 양육하다"},
  {"japanese": "破れる やぶれる", "korean": "찢어지다"},
  {"japanese": "譲る ゆずる", "korean": "양보하다, 양도하다"},
  {"japanese": "輸入する ゆにゅうする", "korean": "수입하다"},
  {"japanese": "許す ゆるす", "korean": "용서하다, 허락하다"},
  {"japanese": "緩む ゆるむ", "korean": "느슨해지다"},
  {"japanese": "汚れる よごれる", "korean": "더러워지다"},
  {"japanese": "寄せる よせる", "korean": "밀려오다, 다가오다"},
  {"japanese": "呼び止める よびとめる", "korean": "불러 세우다"},
  {"japanese": "寄る よる", "korean": "들르다"},
  {"japanese": "略す りゃくす", "korean": "생략하다, 줄이다"},
  {"japanese": "湧く わく", "korean": "끓다"},
  {"japanese": "渡る わたる", "korean": "건너다"},
  {"japanese": "割り込む わりこむ", "korean": "끼어들다"},
  {"japanese": "厚い あつい", "korean": "두껍다"},
  {"japanese": "怪しい あやしい", "korean": "수상하다, 이상하다"},
  {"japanese": "荒い あらい", "korean": "거칠다"},
  {"japanese": "痛ましい いたましい", "korean": "가엽다, 애처롭다"},
  {"japanese": "薄暗い うすぐらい", "korean": "어슴푸레하다"},
  {"japanese": "思いがけない おもいがけない", "korean": "의외이다, 뜻밖이다"},
  {"japanese": "重苦しい おもくるしい", "korean": "답답하다, 숨막히다"},
  {"japanese": "浅い あさい", "korean": "얕다"},
  {"japanese": "慌ただしい あわただしい", "korean": "분주하다"},
  {"japanese": "偉い えらい", "korean": "훌륭하다, 위대하다"},
  {"japanese": "幼い おさない", "korean": "어리다"},
  {"japanese": "恐ろしい おそろしい", "korean": "두렵다, 무섭다"},
  {"japanese": "危うい あやうい", "korean": "위태롭다"},
  {"japanese": "厳しい きびしい", "korean": "엄하다, 엄격하다"},
  {"japanese": "悔しい くやしい", "korean": "분하다, 억울하다"},
  {"japanese": "詳しい くわしい", "korean": "상세하다, 자세하다"},
  {"japanese": "険しい けわしい", "korean": "험하다"},
  {"japanese": "細かい こまかい", "korean": "세세하다"},
  {"japanese": "寂しい さびしい", "korean": "쓸쓸하다, 외롭다"},
  {"japanese": "騒がしい さわがしい", "korean": "시끄럽다, 떠들썩하다"},
  {"japanese": "鋭い するどい", "korean": "예리하다"},
  {"japanese": "騒々しい そうぞうしい", "korean": "시끄럽다, 떠들썩하다"},
  {"japanese": "頼もしい たのもしい", "korean": "든든하다"},
  {"japanese": "乏しい とぼしい", "korean": "빈곤하다"},
  {"japanese": "辛い つらい", "korean": "괴롭다"},
  {"japanese": "力強い ちからづよい", "korean": "마음 든든하다, 힘차다"},
  {"japanese": "情けない なさけない", "korean": "한심하다"},
  {"japanese": "名高い なだかい", "korean": "유명하다"},
  {"japanese": "懐かし なつかしい", "korean": "그립다"},
  {"japanese": "憎い にくい", "korean": "밉다"},
  {"japanese": "鈍い にぶい", "korean": "둔하다, 둔탁하다"},
  {"japanese": "温い ぬるい", "korean": "미지근하다"},
  {"japanese": "望ましい のぞましい", "korean": "바람직하다"},
  {"japanese": "激しい はげしい", "korean": "격하다, 심하다"},
  {"japanese": "貧しい まずしい", "korean": "가난하다"},
  {"japanese": "眩しい まぶしい", "korean": "눈부시다"},
  {"japanese": "丸い まるい", "korean": "둥글다"},
  {"japanese": "珍しい めずらしい", "korean": "흔치않다"},
  {"japanese": "申し訳ない もうしわけない", "korean": "죄송하다"},
  {"japanese": "物足りない ものたりない", "korean": "부족하다"},
  {"japanese": "柔らかい やわらかい", "korean": "부드럽다"},
  {"japanese": "緩い ゆるい", "korean": "완만하다"},
  {"japanese": "若々しい わかわかしい", "korean": "아주 젊다, 생기발랄하다"},
  {"japanese": "曖昧だ あいまいだ", "korean": "애매하다"},
  {"japanese": "明らかだ あきらかだ", "korean": "명백하다, 뚜렷하다"},
  {"japanese": "新ただ あらただ", "korean": "새롭다"},
  {"japanese": "安易だ あんいだ", "korean": "안이하다"},
  {"japanese": "大げさだ おおげさだ", "korean": "과장되다"},
  {"japanese": "大ざっぱだ おおざっぱだ", "korean": "대충이다"},
  {"japanese": "穏やかだ おだやかだ", "korean": "온화하다"},
  {"japanese": "快晴だ かいせいだ", "korean": "쾌청하다"},
  {"japanese": "勝手だ かってだ", "korean": "제멋대로다"},
  {"japanese": "簡潔だ かんけつだ", "korean": "간결하다"},
  {"japanese": "頑丈だ がんじょうだ", "korean": "튼튼하다"},
  {"japanese": "簡略だ かんりゃくだ", "korean": "간략하다"},
  {"japanese": "危険だ きけんだ", "korean": "위험하다"},
  {"japanese": "貴重だ きちょうだ", "korean": "귀중하다"},
  {"japanese": "強烈だ きょうれつだ", "korean": "강렬하다"},
  {"japanese": "気楽だ きらくだ", "korean": "마음편하다"},
  {"japanese": "好調だ こうちょうだ", "korean": "호조를 보이다, 순조롭다"},
  {"japanese": "幸いだ さいわいだ", "korean": "다행이다"},
  {"japanese": "盛んだ さかんだ", "korean": "번성하다, 왕성하다"},
  {"japanese": "残念だ ざんねんだ", "korean": "유감이다"},
  {"japanese": "じみだ 수수하다", "korean": ""},
  {"japanese": "重要だ じゅうようだ", "korean": "중요하다"},
  {"japanese": "正直だ しょうじきだ", "korean": "정직하다"},
  {"japanese": "深刻だ しんこくだ", "korean": "심각하다"},
  {"japanese": "慎重だ しんちょうだ", "korean": "신중하다"},
  {"japanese": "素直だ すなおだ", "korean": "고분고분하다, 순하다, 솔직하다"},
  {"japanese": "清潔だ せいけつだ", "korean": "청결하다"},
  {"japanese": "率直だ そっちょくだ", "korean": "솔직하다"},
  {"japanese": "粗末だ そまつだ", "korean": "허술하다"},
  {"japanese": "退屈だ たいくつだ", "korean": "지루하다"},
  {"japanese": "対等だ たいとうだ", "korean": "대등하다"},
  {"japanese": "平だ たいらだ", "korean": "평평하다"},
  {"japanese": "確かだ たしかだ", "korean": "확실하다"},
  {"japanese": "多大だ ただいだ", "korean": "많고 크다"},
  {"japanese": "多様だ たようだ", "korean": "다양하다"},
  {"japanese": "丁寧だ ていねいだ", "korean": "정중하다"},
  {"japanese": "適切だ てきせつだ", "korean": "적절하다"},
  {"japanese": "同様だ どうようだ", "korean": "다름없다, 마찬가지다"},
  {"japanese": "得意だ とくいだ", "korean": "잘하다, 자신 있다"},
  {"japanese": "苦手だ にがてだ", "korean": "못하다, 싫어하다"},
  {"japanese": "賑やかだ にぎやかだ", "korean": "번화하다"},
  {"japanese": "派手だ はでだ", "korean": "화려하다"},
  {"japanese": "複雑だ ふくざつだ", "korean": "복잡하다"},
  {"japanese": "不思議だ ふしぎだ", "korean": "이상하다, 불가사의하다"},
  {"japanese": "不調だ ふちょうだ", "korean": "상태가 나쁘다, 부진하다"},
  {"japanese": "物騒だ ぶっそうだ", "korean": "어수선하다, 뒤숭숭하다"},
  {"japanese": "平気だ へいきだ", "korean": "태연하다, 아무렇지 않다"},
  {"japanese": "平凡だ へいぼんだ", "korean": "평범하다"},
  {"japanese": "豊富だ ほうふだ", "korean": "풍부하다"},
  {"japanese": "見事だ みごとだ", "korean": "훌륭하다"},
  {"japanese": "妙だ みょうだ", "korean": "묘하다"},
  {"japanese": "無駄だ むだだ", "korean": "쓸데없다, 허비하다"},
  {"japanese": "迷惑だ めいわくだ", "korean": "민폐이다"},
  {"japanese": "面倒だ めんどうだ", "korean": "귀찮다"},
  {"japanese": "豊かだ ゆたかだ", "korean": "풍족하다, 풍부하다"},
  {"japanese": "余計だ よけいだ", "korean": "쓸데없다"},
  {"japanese": "利口だ りこうだ", "korean": "영리하다"},
  {"japanese": "立派だ りっぱだ", "korean": "훌륭하다"},
  {"japanese": "冷静だ れいせいだ", "korean": "냉철하다, 이성적이다"},
  {"japanese": "愛用 あいよう", "korean": "애용"},
  {"japanese": "印象 いんしょう", "korean": "인상"},
  {"japanese": "引用 いんよう", "korean": "인용"},
  {"japanese": "売上 うりあげ", "korean": "매상"},
  {"japanese": "遠慮 えんりょ", "korean": "사양, 삼가"},
  {"japanese": "温暖 おんだん", "korean": "온난"},
  {"japanese": "解決 かいけつ", "korean": "해결"},
  {"japanese": "解消 かいしょう", "korean": "해소"},
  {"japanese": "拡充 かくじゅう", "korean": "확충"},
  {"japanese": "確認 かくにん", "korean": "확인"},
  {"japanese": "価値 かち", "korean": "가치"},
  {"japanese": "活発 かっぱつ", "korean": "활발"},
  {"japanese": "活躍 かつやく", "korean": "활약"},
  {"japanese": "勧誘 かんゆう", "korean": "권유"},
  {"japanese": "簡略 かんりゃく", "korean": "간략"},
  {"japanese": "規格 きかく", "korean": "규격"},
  {"japanese": "企業 きぎょう", "korean": "기업"},
  {"japanese": "技術 ぎじゅつ", "korean": "기술"},
  {"japanese": "議論 ぎろん", "korean": "논의"},
  {"japanese": "緊張 きんちょう", "korean": "긴장"},
  {"japanese": "傾向 けいこう", "korean": "경향"},
  {"japanese": "現状 げんじょう", "korean": "현상"},
  {"japanese": "講義 こうぎ", "korean": "강의"},
  {"japanese": "購入 こうにゅう", "korean": "구입"},
  {"japanese": "好評 こうひょう", "korean": "호평"},
  {"japanese": "採用 さいよう", "korean": "채용"},
  {"japanese": "資源 しげん", "korean": "자원"},
  {"japanese": "姿勢 しせい", "korean": "자세"},
  {"japanese": "指導 しどう", "korean": "지도"},
  {"japanese": "地元 じもと", "korean": "그 고장, 그 지방"},
  {"japanese": "循環 じゅんかん", "korean": "순환"},
  {"japanese": "状況 じょうきょう", "korean": "상황"},
  {"japanese": "条件 じょうけん", "korean": "조건"},
  {"japanese": "証拠 しょうこ", "korean": "증거"},
  {"japanese": "詳細 しょうさい", "korean": "상세"},
  {"japanese": "象徴 しょうちょう", "korean": "상징"},
  {"japanese": "診断 しんだん", "korean": "진단"},
  {"japanese": "進歩 しんぽ", "korean": "진보"},
  {"japanese": "信頼 しんらい", "korean": "신뢰"},
  {"japanese": "製造 せいぞう", "korean": "제조"},
  {"japanese": "制約 せいやく", "korean": "제약"},
  {"japanese": "責任 せきにん", "korean": "책임"},
  {"japanese": "設置 せっち", "korean": "설치"},
  {"japanese": "宣伝 せんでん", "korean": "선전"},
  {"japanese": "専念 せんねん", "korean": "전념"},
  {"japanese": "増加 ぞうか", "korean": "증가"},
  {"japanese": "態度 たいど", "korean": "태도"},
  {"japanese": "担当 たんとう", "korean": "담당"},
  {"japanese": "長所 ちょうしょ", "korean": "장점"},
  {"japanese": "調節 ちょうせつ", "korean": "조절"},
  {"japanese": "特徴 とくちょう", "korean": "특징"},
  {"japanese": "特定 とくてい", "korean": "특정"},
  {"japanese": "特別 とくべつ", "korean": "특별"},
  {"japanese": "土地 とち", "korean": "토지"},
  {"japanese": "波 なみ", "korean": "파도"},
  {"japanese": "涙 なみだ", "korean": "눈물"},
  {"japanese": "温もり ぬくもり", "korean": "온기, 따스함, 체온"},
  {"japanese": "値段 ねだん", "korean": "가격"},
  {"japanese": "農産物 のうさんぶつ", "korean": "농산물"},
  {"japanese": "能率 のうりつ", "korean": "능률"},
  {"japanese": "把握 はあく", "korean": "파악"},
  {"japanese": "配達 はいたつ", "korean": "배달"},
  {"japanese": "俳優 はいゆう", "korean": "배우"},
  {"japanese": "配慮 はいりょ", "korean": "배려"},
  {"japanese": "破壊 はかい", "korean": "파괴"},
  {"japanese": "肌 はだ", "korean": "피부"},
  {"japanese": "発揮 はっき", "korean": "발휘"},
  {"japanese": "発行 はっこう", "korean": "발행"},
  {"japanese": "発送 はっそう", "korean": "발송"},
  {"japanese": "発売 はつばい", "korean": "발매"},
  {"japanese": "幅 はば", "korean": "폭"},
  {"japanese": "範囲 はんい", "korean": "범위"},
  {"japanese": "反映 はんえい", "korean": "반영"},
  {"japanese": "半額 はんがく", "korean": "반액"},
  {"japanese": "半減 はんげん", "korean": "반감"},
  {"japanese": "判断 はんだん", "korean": "판단"},
  {"japanese": "反応 はんのう", "korean": "반응"},
  {"japanese": "販売 はんばい", "korean": "판매"},
  {"japanese": "筆者 ひっしゃ", "korean": "필자"},
  {"japanese": "飛躍的 ひやくてき", "korean": "비약적"},
  {"japanese": "費用 ひよう", "korean": "비용"},
  {"japanese": "評価 ひょうか", "korean": "평가"},
  {"japanese": "風景 ふうけい", "korean": "풍경"},
  {"japanese": "不可欠 ふかけつ", "korean": "불가결"},
  {"japanese": "不足 ふそく", "korean": "부족"},
  {"japanese": "負担 ふたん", "korean": "부담"},
  {"japanese": "普遍的 ふへんてき", "korean": "보편적"},
  {"japanese": "不良品 ふりょうひん", "korean": "불량품"},
  {"japanese": "分析 ぶんせき", "korean": "분석"},
  {"japanese": "弊社 へいしゃ", "korean": "자기 회사의 겸칭"},
  {"japanese": "平和 へいわ", "korean": "평화"},
  {"japanese": "変換 へんかん", "korean": "변환"},
  {"japanese": "変更 へんこう", "korean": "변경"},
  {"japanese": "法律 ほうりつ", "korean": "법률"},
  {"japanese": "保護者 ほごしゃ", "korean": "보호자"},
  {"japanese": "募集 ぼしゅう", "korean": "모집"},
  {"japanese": "本質 ほんしつ", "korean": "본질"},
  {"japanese": "本物 ほんもの", "korean": "진짜, 실물"},
  {"japanese": "見た目 みため", "korean": "겉모습"},
  {"japanese": "魅力 みりょく", "korean": "매력"},
  {"japanese": "名刺 めいし", "korean": "명함"},
  {"japanese": "模型 もけい", "korean": "모형"},
  {"japanese": "模範 もはん", "korean": "모범"},
  {"japanese": "遊園地 ゆうえんち", "korean": "유원지"},
  {"japanese": "有効 ゆうこう", "korean": "유효"},
  {"japanese": "優勝 ゆうしょう", "korean": "우승"},
  {"japanese": "夢 ゆめ", "korean": "꿈"},
  {"japanese": "要求 ようきゅう", "korean": "요구"},
  {"japanese": "様子 ようす", "korean": "모습, 모양"},
  {"japanese": "世の中 よのなか", "korean": "세상"},
  {"japanese": "余裕 よゆう", "korean": "여유"},
  {"japanese": "楽天的 らくてんてき", "korean": "낙천적"},
  {"japanese": "利益 りえき", "korean": "이익"},
  {"japanese": "利点 りてん", "korean": "이점"},
  {"japanese": "歴史 れきし", "korean": "역사"},
  {"japanese": "割引 わりびき", "korean": "할인"},
  {"japanese": "相変わらず あいかわらず", "korean": "변함없이"},
  {"japanese": "相次いで あいついで", "korean": "잇따라"},
  {"japanese": "改めて あらためて", "korean": "다시, 재차"},
  {"japanese": "案外 あんがい", "korean": "의외로"},
  {"japanese": "生き生き いきいき", "korean": "생생한 모양, 활기찬 모양"},
  {"japanese": "一応 いちおう", "korean": "일단"},
  {"japanese": "一斉に いっせいに", "korean": "일제히"},
  {"japanese": "一体 いったい", "korean": "대체"},
  {"japanese": "今にも いまにも", "korean": "금방이라도"},
  {"japanese": "大いに おおいに", "korean": "크게, 매우"},
  {"japanese": "各々 おのおの", "korean": "각각"},
  {"japanese": "思わず おもわず", "korean": "무심코"},
  {"japanese": "必ず かならず", "korean": "반드시, 꼭"},
  {"japanese": "必ずしも かならずしも", "korean": "반드시 ~인 것은 아니다"},
  {"japanese": "偶然 ぐうぜん", "korean": "우연히"},
  {"japanese": "幸いに さいわいに", "korean": "다행히"},
  {"japanese": "先ほど さきほど", "korean": "아까, 먼저"},
  {"japanese": "早速 さっそく", "korean": "즉시, 조속히"},
  {"japanese": "様々 さまざま", "korean": "여러 가지"},
  {"japanese": "強いて しいて", "korean": "굳이, 구태여"},
  {"japanese": "直に じかに", "korean": "직접"},
  {"japanese": "次第に しだいに", "korean": "점점, 순차적으로"},
  {"japanese": "実に じつに", "korean": "실제로"},
  {"japanese": "十分 じゅうぶん", "korean": "충분"},
  {"japanese": "徐々に じょじょに", "korean": "서서히"},
  {"japanese": "少なくとも すくなくとも", "korean": "적어도"},
  {"japanese": "絶対に ぜったいに", "korean": "절대로"},
  {"japanese": "相当 そうとう", "korean": "상당히"},
  {"japanese": "続々 ぞくぞく", "korean": "속속, 계속해서"},
  {"japanese": "大抵 たいてい", "korean": "대체로"},
  {"japanese": "絶えず たえず", "korean": "끊임없이"},
  {"japanese": "多少 たしょう", "korean": "다소"},
  {"japanese": "直ちに ただちに", "korean": "금새"},
  {"japanese": "単なる たんなる", "korean": "단순한"},
  {"japanese": "着々 ちゃくちゃく", "korean": "착착"},
  {"japanese": "常に つねに", "korean": "항상, 언제나"},
  {"japanese": "突然 とつぜん", "korean": "돌연, 갑자기"},
  {"japanese": "何しろ なにしろ", "korean": "아무튼, 어쨌든"},
  {"japanese": "何とか なんとか", "korean": "뭐라고, 어떻게든"},
  {"japanese": "果たして はたして", "korean": "과연"},
  {"japanese": "再び ふたたび", "korean": "다시, 재차"},
  {"japanese": "別々 べつべつ", "korean": "따로따로"},
  {"japanese": "全く まったく", "korean": "전혀"},
  {"japanese": "最も もっとも", "korean": "가장"},
  {"japanese": "元々 もともと", "korean": "원래"},
  {"japanese": "余計 よけい", "korean": "한층 더, 더욱"}
];

function App() {
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [userInput, setUserInput] = useState('');
  const [message, setMessage] = useState('');

  const handleInputChange = (event) => {
    setUserInput(event.target.value);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    const currentWord = words[currentWordIndex];

    if (userInput === currentWord.korean) {
      setMessage('맞았습니다!');
    } else {
      setMessage(`틀렸습니다. 정답은: ${currentWord.korean}`);
    }

    // 입력 초기화 및 다음 단어로 변경
    setUserInput('');
    setCurrentWordIndex((prevIndex) => (prevIndex + 1) % words.length);
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>단어 학습 프로그램</h1>
        <h2>일본어: {words[currentWordIndex].japanese}</h2>
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            value={userInput}
            onChange={handleInputChange}
            placeholder="뜻을 입력하세요"
          />
          <button type="submit">확인</button>
        </form>
        {message && <p>{message}</p>}
      </header>
    </div>
  );
}

export default App;